/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-29 05:40:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"./css/register_taxi.css\" rel=\"stylesheet\" />\r\n");
      out.write("	<script>\r\n");
      out.write("		function check() {\r\n");
      out.write("/*\r\n");
      out.write("			let taxi_form = document.taxi_form;\r\n");
      out.write("			let regno = taxi_form.regno;\r\n");
      out.write("			let regtime = taxi_form.regtime;\r\n");
      out.write("			let regdate = taxi_form.regdate;\r\n");
      out.write("			let id = taxi_form.id;\r\n");
      out.write("			let startpoint = taxi_form.startpoint;\r\n");
      out.write("			let destination = taxi_form.destination;\r\n");
      out.write("			let taxino = taxi_form.taxino;\r\n");
      out.write("			let state = taxi_form.state;\r\n");
      out.write("\r\n");
      out.write("			if (regno.value == \"\") {\r\n");
      out.write("				alert(\"예약번호를 입력하세요!\");\r\n");
      out.write("				regno.focus();\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (regtime.value == \"\") {\r\n");
      out.write("				alert(\"예약시간을 입력하세요!\");\r\n");
      out.write("				regtime.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (regdate.value == \"\") {\r\n");
      out.write("				alert(\"예약날짜를 입력하세요!\");\r\n");
      out.write("				regdate.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (id.value == \"\") {\r\n");
      out.write("				alert(\"아이디를 입력하세요!\");\r\n");
      out.write("				id.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (startpoint.value == \"\") {\r\n");
      out.write("				alert(\"시작지점을 입력하세요!\");\r\n");
      out.write("				startpoint.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (destination.value == \"\") {\r\n");
      out.write("				alert(\"도착지점을 입력하세요!\");\r\n");
      out.write("				destination.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (taxino.value == \"\") {\r\n");
      out.write("				alert(\"택시번호를 입력하세요!\");\r\n");
      out.write("				taxino.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			} else if (state.value == \"선택하기\") {\r\n");
      out.write("				alert(\"배차상태를 선택하세요!\");\r\n");
      out.write("				state.focus;\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			*/\r\n");
      out.write("			return true;\r\n");
      out.write("		} \r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<form name=\"taxi_form\" action=\"register_action.jsp\" method=\"post\" onsubmit=\"return check()\">\r\n");
      out.write("		<table>\r\n");
      out.write("			<caption><strong>택시 예약 등록</strong></caption>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>예약번호</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"regno\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>예약시간</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"regtime\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>예약날짜</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"regdate\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>고객아이디</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"id\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>출발지</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"startpoint\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>목적지</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"destination\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>택시번호</td>\r\n");
      out.write("				<td><input type=\"text\" name=\"taxino\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>배차상태</td>\r\n");
      out.write("				<td><select name=\"state\">\r\n");
      out.write("						<option value=\"선택하기\">선택하기</option>\r\n");
      out.write("						<option value=\"P\">배차완료</option>\r\n");
      out.write("						<option value=\"R\">배차준비</option>\r\n");
      out.write("						<option value=\"X\">배차미정</option>\r\n");
      out.write("					</select></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\">\r\n");
      out.write("				<button>등록</button>\r\n");
      out.write("					<button>다시입력</button>\r\n");
      out.write("				</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
